var chinatown = [
  {
    "Company_Name": "101 Bakery",
    "company_code": "A1",
    "Address": "56 Beach St",
    "Phone Number Combined": "(617) 451-9988",
    "Website": "https://www.yelp.com/biz/101-bakery-boston",
    "Reviews": 49,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "BAKERY",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "163 Vietnam Sandwich",
    "company_code": "A2",
    "Address": "66 Harrison Ave",
    "Phone Number Combined": "(617) 542-7903",
    "Website": "https://www.yelp.com/biz/163-vietnamese-sandwiches-and-bubble-tea-boston",
    "Reviews": 79,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "SANDWICH",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Abby Lane Food & Spirits",
    "company_code": "A3",
    "Address": "255 Tremont St",
    "Phone Number Combined": "(617) 451-2229",
    "Website": "https://www.abbylaneboston.com",
    "Reviews": 497,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 2,
    "price": "$$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Alchemista",
    "company_code": "A4",
    "Address": "164 Lincoln St",
    "Phone Number Combined": "(617) 202-5253",
    "Website": "https://www.alchemista.com",
    "Reviews": 10,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.2,
    "price_num": 0,
    "price": "Unknown",
    "type": "CATERER",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Artisan Bistro",
    "company_code": "A5",
    "Address": "10 Avery St",
    "Phone Number Combined": "(617) 574-7176",
    "Website": "https://www.ritzcarlton.com/en/hotels/boston/dining/artisan-bistro",
    "Reviews": 67,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.1,
    "price_num": 3,
    "price": "$$$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Asian Garden Restaurant",
    "company_code": "A6",
    "Address": "28 Harrison Ave # 1",
    "Phone Number Combined": "(617) 695-1646",
    "Website": "https://www.asiangardenboston.com",
    "Reviews": 200,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Au Bon Pain",
    "company_code": "A7",
    "Address": "800 Washington St",
    "Phone Number Combined": "(617) 636-4470",
    "Website": "https://www.aubonpain.com",
    "Reviews": 69,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.9,
    "price_num": 2,
    "price": "$$",
    "type": "RESTAURANT",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Authentic China House Inc",
    "company_code": "A8",
    "Address": "55 Beach St",
    "Phone Number Combined": "Not Available",
    "Website": "unknown",
    "Reviews": 1,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Avana Sushi",
    "company_code": "A9",
    "Address": "42 Beach St",
    "Phone Number Combined": "(617) 818-7782",
    "Website": "https://www.avanasushi.com",
    "Reviews": 424,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "SUSHI",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Avenue One",
    "company_code": "A10",
    "Address": "1 Avenue DE Lafayette # 3",
    "Phone Number Combined": "(617) 422-5579",
    "Website": "https://www.yelp.com/biz/avenue-one-boston",
    "Reviews": 146,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "B Good LLC",
    "company_code": "A11",
    "Address": "109 Kingston St # 3r",
    "Phone Number Combined": "(508) 878-2766",
    "Website": "https://www.bgood.com",
    "Reviews": 235,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 2,
    "price": "$$",
    "type": "HEALTH FOOD",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Back Deck",
    "company_code": "A12",
    "Address": "2 West St",
    "Phone Number Combined": "(617) 670-0320",
    "Website": "http://www.backdeckboston.com/content/welcome-back-deck",
    "Reviews": 900,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Beard Papa's",
    "company_code": "A13",
    "Address": "31 Harrison Ave # A",
    "Phone Number Combined": "(857) 263-7169",
    "Website": "https://www.yelp.com/biz/beard-papas-boston-4",
    "Reviews": 288,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "PASTRY SHOP",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Best Bar-B-Que Kitchen Inc",
    "company_code": "A14",
    "Address": "86 Beach St",
    "Phone Number Combined": "(617) 399-0285",
    "Website": "https://www.yelp.com/biz/best-bar-b-q-restaurant-boston",
    "Reviews": 13,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.5,
    "price_num": 0,
    "price": "Unknown",
    "type": "BARBECUE",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Blackbird Doughnuts",
    "company_code": "A15",
    "Address": "492 Tremont St",
    "Phone Number Combined": "(617) 482-9000",
    "Website": "https://www.blackbirddoughnuts.com/menus",
    "Reviews": 666,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "DONUT",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Blaze Pizza",
    "company_code": "A16",
    "Address": "123 Stuart St",
    "Phone Number Combined": "(617) 297-9586",
    "Website": "https://www.blazepizza.com",
    "Reviews": 707,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "PIZZA",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Blu At The Sports Club/LA",
    "company_code": "A17",
    "Address": "4 Avery St # 4",
    "Phone Number Combined": "(617) 375-8550",
    "Website": "https://www.yelp.com/biz/blu-restaurant-and-bar-boston",
    "Reviews": 203,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 3,
    "price": "$$$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Blu Restaurant",
    "company_code": "A18",
    "Address": "4 Avery St # 4",
    "Phone Number Combined": "(617) 375-8550",
    "Website": "http://www.blurestaurant.com",
    "Reviews": 203,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.2,
    "price_num": 3,
    "price": "$$$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Boloco",
    "company_code": "A19",
    "Address": "176 Boylston St",
    "Phone Number Combined": "(617) 778-6772",
    "Website": "http://www.boloco.com",
    "Reviews": 359,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "MEXICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Boston Chinese Freemasons",
    "company_code": "A20",
    "Address": "23 Beach St # 4",
    "Phone Number Combined": "(781) 964-5189",
    "Website": "https://www.bostonchinesefreemasons.org",
    "Reviews": 2,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 5,
    "price_num": 0,
    "price": "Unknown",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Boston Kitchen",
    "company_code": "A21",
    "Address": "1 Stuart St",
    "Phone Number Combined": "(617) 482-0085",
    "Website": "http://www.bostonkitchenpizza.com",
    "Reviews": 484,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "PIZZA",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Bubor Cha Cha",
    "company_code": "A22",
    "Address": "45 Beach St",
    "Phone Number Combined": "(617) 482-3338",
    "Website": "http://www.buborchacha.com",
    "Reviews": 339,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.7,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Buca Inc",
    "company_code": "A23",
    "Address": "8n West St",
    "Phone Number Combined": "(617) 567-5228",
    "Website": "unknown",
    "Reviews": 1,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.8,
    "price_num": 1,
    "price": "$",
    "type": "ITALIAN",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Cafe Corner",
    "company_code": "A24",
    "Address": "62 Harrison Ave",
    "Phone Number Combined": "(617) 338-1988",
    "Website": "https://www.yelp.com/biz/cafe-corner-boston",
    "Reviews": 48,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.2,
    "price_num": 0,
    "price": "Unknown",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Caffe Nero",
    "company_code": "A25",
    "Address": "560 Washington St",
    "Phone Number Combined": "(617) 936-3432",
    "Website": "https://caffenero.com/us/",
    "Reviews": 958,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Cajun & Grill",
    "company_code": "A26",
    "Address": "720 Atlantic Ave",
    "Phone Number Combined": "(617) 439-8687",
    "Website": "http://cajunsouthwestgrill.com",
    "Reviews": 19,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.2,
    "price_num": 0,
    "price": "Unknown",
    "type": "RESTAURANT",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Cha Time",
    "company_code": "A27",
    "Address": "31 Harrison Ave",
    "Phone Number Combined": "(617) 982-6928",
    "Website": "https://www.yelp.com/biz/chatime-boston",
    "Reviews": 207,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "TEA",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "China King",
    "company_code": "A28",
    "Address": "60 Beach St",
    "Phone Number Combined": "(617) 542-1763",
    "Website": "https://www.chinakingbostonma.com",
    "Reviews": 242,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "China Pearl",
    "company_code": "A29",
    "Address": "9 Tyler St",
    "Phone Number Combined": "(617) 426-4338",
    "Website": "https://www.yelp.com/biz/china-pearl-restaurant-boston",
    "Reviews": 748,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Chinatown Cafe",
    "company_code": "A30",
    "Address": "262 Harrison Ave",
    "Phone Number Combined": "(617) 695-9888",
    "Website": "Chinatowncafedenton.Com",
    "Reviews": null,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Clay Pot Cafe",
    "company_code": "A31",
    "Address": "74 Kneeland St",
    "Phone Number Combined": "(617) 357-5262",
    "Website": "https://www.yelp.com/biz/clay-pot-cafe-boston",
    "Reviews": 281,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Corner Pub",
    "company_code": "A32",
    "Address": "162 Lincoln St",
    "Phone Number Combined": "(617) 542-7080",
    "Website": "https://cornerpubboston.net",
    "Reviews": 400,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "BAR",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Crave-Mad For Chicken",
    "company_code": "A33",
    "Address": "75 Kneeland St # 4",
    "Phone Number Combined": "(617) 338-0188",
    "Website": "http://cravemadforchicken.com",
    "Reviews": 992,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 2,
    "price": "$$",
    "type": "KOREAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Crown Royal Bakery",
    "company_code": "A34",
    "Address": "23 Edinboro St",
    "Phone Number Combined": "(617) 338-8889",
    "Website": "https://www.yelp.com/biz/crown-royal-bakery-boston-2",
    "Reviews": 11,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.8,
    "price_num": 0,
    "price": "Unknown",
    "type": "BAKERY",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Ct Sweet Kingdom",
    "company_code": "A35",
    "Address": "15 Beach St # 1",
    "Phone Number Combined": "(617) 338-8885",
    "Website": "https://www.yelp.com/biz/ct-sweet-kingdom-boston",
    "Reviews": 175,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.1,
    "price_num": 0,
    "price": "Unknown",
    "type": "DESSERT",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Dong Khanh",
    "company_code": "A36",
    "Address": "81 Harrison Ave",
    "Phone Number Combined": "(617) 426-9410",
    "Website": "https://www.yelp.com/biz/new-dong-khanh-boston-2",
    "Reviews": 305,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "VIETNAMESE",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Dumpling Cafe Inc",
    "company_code": "A37",
    "Address": "697 Washington St",
    "Phone Number Combined": "(617) 338-8858",
    "Website": "https://www.dumplingcafe.com",
    "Reviews": 1142,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.9,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Dumpling King",
    "company_code": "A38",
    "Address": "40 Harrison Ave",
    "Phone Number Combined": "(617) 482-8888",
    "Website": "https://www.yelp.com/biz/dumpling-king-boston",
    "Reviews": 28,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.6,
    "price_num": 0,
    "price": "Unknown",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Dunkin'",
    "company_code": "A39",
    "Address": "16 Kneeland St # 18",
    "Phone Number Combined": "(617) 695-0546",
    "Website": "https://www.dunkindonuts.com/en",
    "Reviews": 70,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.8,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Dunkin'",
    "company_code": "A40",
    "Address": "630 Washington St # C02",
    "Phone Number Combined": "(617) 426-9731",
    "Website": "https://www.dunkindonuts.com/en",
    "Reviews": 7,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.7,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Dunkin'",
    "company_code": "A41",
    "Address": "750 Washington St",
    "Phone Number Combined": "(617) 542-6165",
    "Website": "https://www.dunkindonuts.com/en",
    "Reviews": 166,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.9,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Eldo Cake House",
    "company_code": "A42",
    "Address": "36 Harrison Ave",
    "Phone Number Combined": "(617) 350-7977",
    "Website": "https://www.yelp.com/biz/eldo-cake-house-boston-2",
    "Reviews": 169,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "BAKERY",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Empire Garden Restaurant",
    "company_code": "A43",
    "Address": "690 Washington St",
    "Phone Number Combined": "(617) 482-8898",
    "Website": "https://www.yelp.com/biz/empire-garden-restaurant-boston-2",
    "Reviews": 455,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.8,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Encore Lounge",
    "company_code": "A44",
    "Address": "275 Tremont St",
    "Phone Number Combined": "(617) 728-2162",
    "Website": "https://www.yelp.com/biz/encore-lounge-boston",
    "Reviews": 47,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Felt",
    "company_code": "A45",
    "Address": "533 Washington St",
    "Phone Number Combined": "(617) 350-5555",
    "Website": "https://www.yelp.com/biz/felt-boston",
    "Reviews": 170,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 2.5,
    "price_num": 2,
    "price": "$$",
    "type": "FRENCH",
    "cuisine": "French",
    "": null
  },
  {
    "Company_Name": "Figaro's",
    "company_code": "A46",
    "Address": "105 Beach St # 1",
    "Phone Number Combined": "(617) 426-2121",
    "Website": "http://www.figarosboston.com/",
    "Reviews": 216,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.7,
    "price_num": 1,
    "price": "$",
    "type": "SANDWICH",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Fin's Sushi & Grill",
    "company_code": "A47",
    "Address": "62 Boylston St",
    "Phone Number Combined": "(617) 423-4888",
    "Website": "http://www.finsboston.com/",
    "Reviews": 233,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.3,
    "price_num": 2,
    "price": "$$",
    "type": "JAPANESE",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Five Spices House",
    "company_code": "A48",
    "Address": "58 Beach St",
    "Phone Number Combined": "(617) 574-8888",
    "Website": "http://www.5spiceshouse.com/",
    "Reviews": 346,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Fourth Wall Restaurant & Bar",
    "company_code": "A49",
    "Address": "228 Tremont St",
    "Phone Number Combined": "(857) 957-0909",
    "Website": "http://places.singleplatform.com/4th-wall/menu?ref=google",
    "Reviews": 147,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "BAR",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "C-Mart Supermarket",
    "company_code": "A50",
    "Address": "109 Lincoln St",
    "Phone Number Combined": "(617) 426-8888",
    "Website": "https://www.supergmart.net/",
    "Reviews": 527,
    "Credit_num": 2,
    "Credit_Score": "C+",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "SUPERMARKET",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Genghis Chinese Food Inc",
    "company_code": "A51",
    "Address": "57 Harvard St",
    "Phone Number Combined": "Not Available",
    "Website": "genghissalem.com",
    "Reviews": 20,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Genki Ya",
    "company_code": "A52",
    "Address": "232 Tremont St",
    "Phone Number Combined": "(617) 338-8686",
    "Website": "http://www.genkiyasushi.com/",
    "Reviews": 566,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.1,
    "price_num": 2,
    "price": "$$",
    "type": "JAPANESE",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Gourmet China Restaurant",
    "company_code": "A53",
    "Address": "23 Tyler St # 1",
    "Phone Number Combined": "(617) 482-9888",
    "Website": "https://www.chinagourmetbostonma.com/",
    "Reviews": 36,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Gourmet Dumpling House",
    "company_code": "A54",
    "Address": "52 Beach St",
    "Phone Number Combined": "(617) 338-6223",
    "Website": "http://www.gourmetchinahouse.com/",
    "Reviews": 574,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Great Barbecue",
    "company_code": "A55",
    "Address": "15 Hudson St",
    "Phone Number Combined": "(617) 728-8699",
    "Website": "https://www.yelp.com/biz/great-barbecue-boston",
    "Reviews": 22,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 2,
    "price": "$$",
    "type": "GRILL",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Great Taste Bakery & Rstrnt",
    "company_code": "A56",
    "Address": "63 Beach St",
    "Phone Number Combined": "(617) 426-8899",
    "Website": "https://www.bostongreattastebakery.com/",
    "Reviews": 283,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Halal Guys",
    "company_code": "A57",
    "Address": "137 Stuart St",
    "Phone Number Combined": "(857) 250-2279",
    "Website": "https://thehalalguys.com/",
    "Reviews": 1241,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Happy Family Food Market",
    "company_code": "A58",
    "Address": "11 Hudson St # A",
    "Phone Number Combined": "(617) 542-1488",
    "Website": "https://www.yelp.com/biz/happy-family-food-market-boston",
    "Reviews": 5,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 3.6,
    "price_num": 2,
    "price": "$$",
    "type": "SUPERMARKET",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Happy Lamb Hot Pot",
    "company_code": "A59",
    "Address": "693 Washington St",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.yelp.com/biz/happy-lamb-hot-pot-cambridge",
    "Reviews": 754,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.5,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Hei LA Moon",
    "company_code": "A60",
    "Address": "88 Beach St",
    "Phone Number Combined": "(617) 338-8813",
    "Website": "http://places.singleplatform.com/hei-la-moon/menu?ref=google",
    "Reviews": 1679,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Hing Shing Pastry",
    "company_code": "A61",
    "Address": "67 Beach St",
    "Phone Number Combined": "(617) 451-1162",
    "Website": "https://www.yelp.com/biz/hing-shing-pastry-boston",
    "Reviews": 64,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "PASTRY SHOP",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Ho Yuen Bakery Inc",
    "company_code": "A62",
    "Address": "54 Beach St # 1",
    "Phone Number Combined": "(617) 426-8320",
    "Website": "https://www.yelp.com/biz/ho-yuen-bakery-boston",
    "Reviews": 55,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "PASTRY SHOP",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Hong Kong Eatery",
    "company_code": "A63",
    "Address": "79 Harrison Ave",
    "Phone Number Combined": "(617) 423-0838",
    "Website": "http://www.hongkongeatery.com/",
    "Reviews": 640,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Hot Eastern Inc",
    "company_code": "A64",
    "Address": "42 Beach St # 1b",
    "Phone Number Combined": "(617) 988-0660",
    "Website": "https://www.hoteastern.com/",
    "Reviews": 249,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.2,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Hot Pot Buffet",
    "company_code": "A65",
    "Address": "70 Beach St # 1",
    "Phone Number Combined": "(617) 338-0808",
    "Website": "https://www.yelp.com/biz/hot-pot-buffet-boston",
    "Reviews": 918,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Irashai Sushi",
    "company_code": "A66",
    "Address": "8 Kneeland St",
    "Phone Number Combined": "(617) 350-6888",
    "Website": "https://www.irashaisushiteriyaki.com/",
    "Reviews": 343,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "JAPANESE",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Jade Garden",
    "company_code": "A67",
    "Address": "20 Tyler St",
    "Phone Number Combined": "(617) 423-3288",
    "Website": "https://www.jadegardensugarland.com/",
    "Reviews": 325,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.9,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Jaho Coffee Roaster & Wine Bar",
    "company_code": "A68",
    "Address": "665 Washington St",
    "Phone Number Combined": "(857) 233-4094",
    "Website": "https://www.jaho.com/pages/downtown-chinatown-jaho",
    "Reviews": 831,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Jia Ho Restaurant",
    "company_code": "A69",
    "Address": "680 Washington St",
    "Phone Number Combined": "Not Available",
    "Website": "https://jaihoatlanta.com/",
    "Reviews": 46,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "INDIAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Jia Ho Supermarket",
    "company_code": "A70",
    "Address": "692 Washington St",
    "Phone Number Combined": "(617) 338-9788",
    "Website": "https://www.google.com/search?q=Jia+Ho+Restaurant&oq=Jia+Ho+Restaurant&aqs=chrome..69i57j0.188j0j9&sourceid=chrome&ie=UTF-8",
    "Reviews": 602,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "SUPERMARKET",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Jooksing Cafe",
    "company_code": "A71",
    "Address": "177 Harrison Ave",
    "Phone Number Combined": "(617) 426-2828",
    "Website": "https://www.jooksingcafe.com/",
    "Reviews": 79,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Juice Republic Inc",
    "company_code": "A72",
    "Address": "200 Lincoln St # 404",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.yelp.com/biz/juice-republic-boston-2",
    "Reviews": 47,
    "Credit_num": 2,
    "Credit_Score": "C+",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "BAR",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Julien Restaurant",
    "company_code": "A73",
    "Address": "250 Franklin St, Boston, MA 02110",
    "Phone Number Combined": "(617) 956-8752",
    "Website": "https://www.allmenus.com/ma/boston/750-julien-restaurant/menu/",
    "Reviews": 1252,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "FRENCH",
    "cuisine": "French",
    "": null
  },
  {
    "Company_Name": "Kaze Shabu Shabu Restaurant",
    "company_code": "A74",
    "Address": "1 Harrison Ave",
    "Phone Number Combined": "(617) 338-8283",
    "Website": "http://www.kazeshabu.com/",
    "Reviews": 492,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 2,
    "price": "$$",
    "type": "JAPANESE",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Kirin Produce Co",
    "company_code": "A75",
    "Address": "22 Oxford St # 24",
    "Phone Number Combined": "(617) 350-8881",
    "Website": "https://www.yelp.com/biz/kirin-produce-boston-2",
    "Reviews": 6,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "SUPERMARKET",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Kneeland Cafe",
    "company_code": "A76",
    "Address": "75 Kneeland St",
    "Phone Number Combined": "(617) 936-3636",
    "Website": "https://www.kneelandcafe.com/",
    "Reviews": 31,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.7,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Kung Fu Tea Boston Chinatown",
    "company_code": "A77",
    "Address": "66 Kneeland St",
    "Phone Number Combined": "(617) 542-8838",
    "Website": "https://tkkbos.lpages.co/catering-kft/",
    "Reviews": 33,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Legal Sea Foods",
    "company_code": "A78",
    "Address": "558 Washington St",
    "Phone Number Combined": "(617) 692-8888",
    "Website": "https://www.legalseafoods.com/",
    "Reviews": 1490,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.5,
    "price_num": 3,
    "price": "$$$",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "Les Zygomates",
    "company_code": "A79",
    "Address": "129 South St # 101",
    "Phone Number Combined": "(617) 542-5108",
    "Website": "https://winebar129.com/",
    "Reviews": 458,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.4,
    "price_num": 3,
    "price": "$$$",
    "type": "BISTRO",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Little Lamb Hot Pot Restaurant",
    "company_code": "A80",
    "Address": "695 Washington St",
    "Phone Number Combined": "(857) 277-1000",
    "Website": "http://www.littlesheep.com/enfranchise/",
    "Reviews": 80,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Little Q Hotpot Restaurant",
    "company_code": "A81",
    "Address": "660 Washington St",
    "Phone Number Combined": "(617) 773-5888",
    "Website": "https://thequsa.com/",
    "Reviews": 205,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Lun Fat Produce",
    "company_code": "A82",
    "Address": "227 Harrison Ave",
    "Phone Number Combined": "(617) 426-4045",
    "Website": "https://www.yelp.com/biz/lunfat-produce-boston",
    "Reviews": 1,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4,
    "price_num": 1,
    "price": "$",
    "type": "SUPERMARKET",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Maria's Taqueria",
    "company_code": "A83",
    "Address": "226 Tremont St",
    "Phone Number Combined": "(617) 357-7399",
    "Website": "https://mariastaqueriaboston.com/",
    "Reviews": 329,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "MEXICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "May's Cake House",
    "company_code": "A84",
    "Address": "223 Harrison Ave # A",
    "Phone Number Combined": "(617) 350-0210",
    "Website": "https://www.yelp.com/biz/mays-cake-house-boston",
    "Reviews": 79,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "PASTRY SHOP",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Mei Sum Bakery Coffee Shop",
    "company_code": "A85",
    "Address": "40 Beach St",
    "Phone Number Combined": "(617) 357-4050",
    "Website": "https://www.yelp.com/biz/mei-sum-boston",
    "Reviews": 43,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "PASTRY SHOP",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Ming Yu Seafood",
    "company_code": "A86",
    "Address": "10 Tyler St",
    "Phone Number Combined": "(617) 542-8081",
    "Website": "https://www.yelp.com/biz/ming-yu-seafood-boston",
    "Reviews": 2,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 1,
    "price_num": 0,
    "price": "Unknown",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "Montien Thai Rstrnt & Lounge",
    "company_code": "A87",
    "Address": "63 Stuart St",
    "Phone Number Combined": "(617) 338-5600",
    "Website": "https://montienthaiboston.com/",
    "Reviews": 621,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.2,
    "price_num": 2,
    "price": "$$",
    "type": "THAILAND",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Moon Villa Restaurant",
    "company_code": "A88",
    "Address": "15 Edinboro St",
    "Phone Number Combined": "(617) 423-2061",
    "Website": "https://www.yelp.com/biz/moon-villa-restaurant-boston",
    "Reviews": 11,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "My Thai Cafe",
    "company_code": "A89",
    "Address": "3 Beach St # 2",
    "Phone Number Combined": "(617) 451-2395",
    "Website": "http://mythaicafeusa.com/",
    "Reviews": 1094,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "THAILAND",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Nam Bac Hong Herbs Inc",
    "company_code": "A90",
    "Address": "75 Harrison Ave # 1",
    "Phone Number Combined": "(617) 426-8227",
    "Website": "http://nambachong.com/Home_Page.html",
    "Reviews": 25,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.1,
    "price_num": 3,
    "price": "$$$",
    "type": "SUPERMARKET",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "New Golden Gate Inc",
    "company_code": "A91",
    "Address": "66 Beach St",
    "Phone Number Combined": "(617) 338-7721",
    "Website": "https://www.goldengateinc.com/",
    "Reviews": 561,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.9,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "New Jumbo Seafood Restaurant",
    "company_code": "A92",
    "Address": "5 Hudson St",
    "Phone Number Combined": "(617) 542-2823",
    "Website": "https://www.newjumboseafoodboston.com/",
    "Reviews": 297,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "New Saigon Sandwich",
    "company_code": "A93",
    "Address": "696 Washington St",
    "Phone Number Combined": "(617) 542-6296",
    "Website": "https://www.yelp.com/biz/new-saigon-sandwich-boston",
    "Reviews": 106,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.6,
    "price_num": 1,
    "price": "$",
    "type": "SANDWICH",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "New Shanghai Restaurant",
    "company_code": "A94",
    "Address": "21 Hudson St",
    "Phone Number Combined": "(617) 338-6688",
    "Website": "https://www.bostonnewshanghai.com/",
    "Reviews": 385,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 3,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "New York Pizza",
    "company_code": "A95",
    "Address": "224 Tremont St # 1",
    "Phone Number Combined": "(617) 482-3459",
    "Website": "http://newyorkpizzaboston.com/",
    "Reviews": 405,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Ocean Treasure Corp",
    "company_code": "A96",
    "Address": "84 Harrison Ave",
    "Phone Number Combined": "(617) 482-0682",
    "Website": "http://www.ocean-treasure.com/",
    "Reviews": 1,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 0,
    "price_num": 0,
    "price": "Unknown",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "Panera Bread",
    "company_code": "A97",
    "Address": "115 Stuart St",
    "Phone Number Combined": "(617) 722-8234",
    "Website": "Panerabread.Com",
    "Reviews": 503,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "DELI",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Peach Farm Restaurant",
    "company_code": "A98",
    "Address": "4 Tyler St # 1",
    "Phone Number Combined": "(617) 482-1116",
    "Website": "Peachfarmboston.Com",
    "Reviews": 438,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.8,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Pearl Villa Chinese Seafood Cf",
    "company_code": "A99",
    "Address": "25 Tyler St",
    "Phone Number Combined": "(617) 338-8770",
    "Website": "Pearlvillaboston.Com",
    "Reviews": 364,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Pekin Duck Supply Corp",
    "company_code": "A100",
    "Address": "11 Edinboro St # 1",
    "Phone Number Combined": "(617) 338-3028",
    "Website": "https://www.yelp.com/biz/pekin-duck-supply-boston",
    "Reviews": 1,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 0,
    "price_num": 0,
    "price": "Unknown",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Penang",
    "company_code": "A101",
    "Address": "685 Washington St",
    "Phone Number Combined": "(617) 451-6373",
    "Website": "Penangmalaysian.Com",
    "Reviews": 989,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.3,
    "price_num": 2,
    "price": "$$",
    "type": "MALAYSIAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Pho Pasteur",
    "company_code": "A102",
    "Address": "682 Washington St",
    "Phone Number Combined": "(617) 482-7467",
    "Website": "Phopasteurboston.Net",
    "Reviews": 1669,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "VIETNAMESE",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Pita Kabob",
    "company_code": "A103",
    "Address": "2 Avenue DE Lafayette",
    "Phone Number Combined": "(617) 542-7482",
    "Website": "Pitakabob.Net",
    "Reviews": 64,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3,
    "price_num": 1,
    "price": "$",
    "type": "MEDITERRANEAN",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Plaza Deli Inc",
    "company_code": "A104",
    "Address": "2 Avery St # 21h",
    "Phone Number Combined": "Not Available",
    "Website": "http://www.plazacateringboston.com/",
    "Reviews": 4,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.2,
    "price_num": 2,
    "price": "$$",
    "type": "DELI",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Potluck Cafe",
    "company_code": "A105",
    "Address": "7 Knapp St",
    "Phone Number Combined": "(617) 482-1188",
    "Website": "http://www.potluckcafe31.com/",
    "Reviews": 82,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.9,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Quic Pic Bbq",
    "company_code": "A106",
    "Address": "50 Beach St",
    "Phone Number Combined": "(617) 426-1110",
    "Website": "Quicpicbbq.Com",
    "Reviews": 157,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.9,
    "price_num": 1,
    "price": "$",
    "type": "BARBECUE",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Rebecca's Cafe",
    "company_code": "A107",
    "Address": "655 Atlantic Ave",
    "Phone Number Combined": "(857) 383-3464",
    "Website": "Rebeccascafe.Com",
    "Reviews": 161,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.6,
    "price_num": 2,
    "price": "$$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Rock Bottom Rstrnt & Brewery",
    "company_code": "A108",
    "Address": "115 Stuart St",
    "Phone Number Combined": "(617) 742-2739",
    "Website": "Rockbottom.Com",
    "Reviews": 470,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.8,
    "price_num": 2,
    "price": "$$",
    "type": "BREW PUB",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Rome Pizza",
    "company_code": "A109",
    "Address": "416 Tremont St",
    "Phone Number Combined": "(617) 695-1640",
    "Website": "Romepizzaboston.Com",
    "Reviews": 784,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "PIZZA",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Ronskys",
    "company_code": "A110",
    "Address": "3 Boylston Pl",
    "Phone Number Combined": "(617) 487-5899",
    "Website": "https://ronskys.com/",
    "Reviews": 76,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.4,
    "price_num": 3,
    "price": "$$$",
    "type": "ITALIAN",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Royal Tea",
    "company_code": "A111",
    "Address": "23 Tyler St",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.royalteaboston.com/",
    "Reviews": 138,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "TEA",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Royale Boston",
    "company_code": "A112",
    "Address": "279 Tremont St",
    "Phone Number Combined": "(617) 338-7699",
    "Website": "Royaleboston.Com",
    "Reviews": 579,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.9,
    "price_num": 2,
    "price": "$$",
    "type": "DRINK",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Ruckus Noddles",
    "company_code": "A113",
    "Address": "5 Tyler St",
    "Phone Number Combined": "(857) 305-3155",
    "Website": "https://www.ruckusboston.com/",
    "Reviews": 351,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.4,
    "price_num": 1,
    "price": "$",
    "type": "NOODLE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Sakura Sunakku",
    "company_code": "A114",
    "Address": "42 Beach St # 101",
    "Phone Number Combined": "(781) 888-3897",
    "Website": "Sakurasunakkuorders.Com",
    "Reviews": 130,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "JAPANESE",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Sal's Pizza",
    "company_code": "A115",
    "Address": "150 Tremont St",
    "Phone Number Combined": "(617) 227-1010",
    "Website": "Sals-Pizza.Com",
    "Reviews": 112,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "ITALIAN",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Salvatore's Restaurant",
    "company_code": "A116",
    "Address": "545 Washington St",
    "Phone Number Combined": "(617) 542-5555",
    "Website": "Salvatoresrestaurants.Com",
    "Reviews": 323,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.1,
    "price_num": 2,
    "price": "$$",
    "type": "ITALIAN",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Sam Hop",
    "company_code": "A117",
    "Address": "44 Beach St # 2111",
    "Phone Number Combined": "(617) 482-1188",
    "Website": "https://www.samueladams.com/",
    "Reviews": 1382,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.7,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Shabu-Zen Restaurant",
    "company_code": "A118",
    "Address": "16 Tyler St",
    "Phone Number Combined": "(617) 292-8828",
    "Website": "Shabuzen.Com",
    "Reviews": 885,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.5,
    "price_num": 2,
    "price": "$$",
    "type": "JAPANESE",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Shing Hong Trading Inc",
    "company_code": "A119",
    "Address": "70 Kneeland St",
    "Phone Number Combined": "(617) 482-2373",
    "Website": "https://www.yelp.com/biz/shing-hong-trading-boston",
    "Reviews": 2,
    "Credit_num": 2,
    "Credit_Score": "C+",
    "rates": 5,
    "price_num": 0,
    "price": "Unknown",
    "type": "ASIAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Shojo",
    "company_code": "A120",
    "Address": "9a Tyler St",
    "Phone Number Combined": "(617) 423-7888",
    "Website": "Shojoboston.Com",
    "Reviews": 781,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "ASIAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Sio Kam Lung Inc",
    "company_code": "A121",
    "Address": "65 Harrison Ave",
    "Phone Number Combined": "(617) 482-8282",
    "Website": "https://www.yelp.com/biz/sio-kam-lung-boston",
    "Reviews": 9,
    "Credit_num": 2,
    "Credit_Score": "C+",
    "rates": 5,
    "price_num": 2,
    "price": "$$",
    "type": "HERB",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Sip Wine Bar & Kitchen",
    "company_code": "A122",
    "Address": "581 Washington St",
    "Phone Number Combined": "(617) 956-0888",
    "Website": "Sipwinebarandkitchen.Com",
    "Reviews": 363,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.2,
    "price_num": 2,
    "price": "$$",
    "type": "BISTRO",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "South East Market",
    "company_code": "A123",
    "Address": "210 Harrison Ave",
    "Phone Number Combined": "(617) 426-4769",
    "Website": "https://www.southeastmarket.com/",
    "Reviews": 93,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "GROCERY",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "South Street Diner",
    "company_code": "A124",
    "Address": "178 Kneeland St",
    "Phone Number Combined": "(617) 350-0028",
    "Website": "Southstreetdiner.Com",
    "Reviews": 2171,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "DINER",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Starbucks",
    "company_code": "A125",
    "Address": "62 Boylston St # 1",
    "Phone Number Combined": "(617) 338-0067",
    "Website": "Starbucks.Com",
    "Reviews": 38,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4,
    "price_num": 2,
    "price": "$$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Starbucks",
    "company_code": "A126",
    "Address": "821 Washington St",
    "Phone Number Combined": "(617) 956-7900",
    "Website": "Starbucks.Com",
    "Reviews": 59,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.2,
    "price_num": 2,
    "price": "$$",
    "type": "COFFEE",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "SUBWAY",
    "company_code": "A127",
    "Address": "230 Tremont St",
    "Phone Number Combined": "(617) 695-1222",
    "Website": "Subway.Com",
    "Reviews": 15,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3,
    "price_num": 1,
    "price": "$",
    "type": "DELI",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Suishaya",
    "company_code": "A128",
    "Address": "2 Tyler St",
    "Phone Number Combined": "(617) 423-3848",
    "Website": "Suishayaboston.Com",
    "Reviews": 369,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.8,
    "price_num": 2,
    "price": "$$",
    "type": "ASIAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Sun Sun Co",
    "company_code": "A129",
    "Address": "16 Oxford St # 1",
    "Phone Number Combined": "(617) 426-6494",
    "Website": "https://www.yelp.com/biz/sun-sun-co-boston-2",
    "Reviews": 16,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "GROCERY",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Susu Gourmet Inc",
    "company_code": "A130",
    "Address": "70 Tyler St",
    "Phone Number Combined": "(617) 338-7388",
    "Website": "Susugourmetboston.Com",
    "Reviews": 72,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Taiwan Cafe",
    "company_code": "A131",
    "Address": "34 Oxford St",
    "Phone Number Combined": "(617) 426-8181",
    "Website": "Taiwancafeboston.Com",
    "Reviews": 675,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.2,
    "price_num": 1,
    "price": "$",
    "type": "ASIAN",
    "cuisine": "Asian",
    "": null
  },
  {
    "Company_Name": "Tam",
    "company_code": "A132",
    "Address": "222 Tremont St",
    "Phone Number Combined": "(617) 770-4048",
    "Website": "https://www.thetamboston.com/",
    "Reviews": 637,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "DRINK",
    "cuisine": "Drink",
    "": "HOME | royaltea boston"
  },
  {
    "Company_Name": "Tastry Cafe Corp",
    "company_code": "A133",
    "Address": "42 Beach St # 101",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.tastycafeboston.com/",
    "Reviews": 149,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "BRUNCH",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Tata Seafood",
    "company_code": "A134",
    "Address": "25 Tyler St",
    "Phone Number Combined": "(617) 338-8770",
    "Website": "Gagaseafoodboston.Com",
    "Reviews": 2289,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.1,
    "price_num": 4,
    "price": "$$$$",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "Tavern Club",
    "company_code": "A135",
    "Address": "4 Boylston Pl",
    "Phone Number Combined": "(617) 338-9682",
    "Website": "Tavernclub.Com",
    "Reviews": 18,
    "Credit_num": 1,
    "Credit_Score": "C",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "Teado",
    "company_code": "A136",
    "Address": "8 Tyler St",
    "Phone Number Combined": "(617) 988-8002",
    "Website": "Teadocafe.Com",
    "Reviews": 880,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "TEA",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Teatro",
    "company_code": "A137",
    "Address": "177 Tremont St # 1",
    "Phone Number Combined": "(617) 778-6841",
    "Website": "Teatroboston.Com",
    "Reviews": 342,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 3,
    "price": "$$$",
    "type": "ITALIAN",
    "cuisine": "Italian",
    "": null
  },
  {
    "Company_Name": "Thinking Cup",
    "company_code": "A138",
    "Address": "165 Tremont St",
    "Phone Number Combined": "(617) 482-5555",
    "Website": "Shop.Thinkingcup.Com",
    "Reviews": 1233,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.5,
    "price_num": 2,
    "price": "$$",
    "type": "TEA",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Top Bread",
    "company_code": "A139",
    "Address": "77 Harrison Ave # 1",
    "Phone Number Combined": "(617) 338-1689",
    "Website": "https://www.yelp.com/biz/top-bread-boston",
    "Reviews": 53,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4,
    "price_num": 1,
    "price": "$",
    "type": "BAKERY",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Townsman",
    "company_code": "A140",
    "Address": "120 Kingston St # 2401",
    "Phone Number Combined": "(617) 993-0750",
    "Website": "Townsmanboston.Com",
    "Reviews": 113,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4,
    "price_num": 3,
    "price": "$$$",
    "type": "BISTRO",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Troquet",
    "company_code": "A141",
    "Address": "107 South St",
    "Phone Number Combined": "(617) 695-9463",
    "Website": "Troquetboston.Com",
    "Reviews": 53,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.4,
    "price_num": 3,
    "price": "$$$",
    "type": "FRENCH",
    "cuisine": "French",
    "": null
  },
  {
    "Company_Name": "Troquet On South",
    "company_code": "A142",
    "Address": "140 Boylston St",
    "Phone Number Combined": "(617) 695-9463",
    "Website": "http://www.troquetboston.com/",
    "Reviews": 238,
    "Credit_num": 3,
    "Credit_Score": "B",
    "rates": 4.6,
    "price_num": 3,
    "price": "$$$",
    "type": "FRENCH",
    "cuisine": "French",
    "": null
  },
  {
    "Company_Name": "Tsaocaa Tea Ma Inc",
    "company_code": "A143",
    "Address": "10a Tyler St",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.tsaocaatea.com/",
    "Reviews": 18,
    "Credit_num": 1,
    "Credit_Score": "C",
    "rates": 3.5,
    "price_num": 1,
    "price": "$",
    "type": "TEA",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Tunnel",
    "company_code": "A144",
    "Address": "100 Stuart St",
    "Phone Number Combined": "(617) 485-4529",
    "Website": "Tunnelboston.Com",
    "Reviews": 70,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 3.1,
    "price_num": 4,
    "price": "$$$$",
    "type": "DRINK",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Turnaround Sushi Inc",
    "company_code": "A145",
    "Address": "75 Kneeland St",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.newsushima.com/",
    "Reviews": 205,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.4,
    "price_num": 2,
    "price": "$$",
    "type": "SUSHI",
    "cuisine": "Japanese",
    "": null
  },
  {
    "Company_Name": "Twin Dragon Seafood Inc",
    "company_code": "A146",
    "Address": "10a Tyler St",
    "Phone Number Combined": "Not Available",
    "Website": "http://twindragonoc.com/",
    "Reviews": 136,
    "Credit_num": 2,
    "Credit_Score": "C+",
    "rates": 3.5,
    "price_num": 2,
    "price": "$$",
    "type": "SEAFOOD",
    "cuisine": "Seafood",
    "": null
  },
  {
    "Company_Name": "Two Peck Crispy Chicken Boston",
    "company_code": "A147",
    "Address": "3 Oak St # C",
    "Phone Number Combined": "Not Available",
    "Website": "https://www.yelp.com/biz/two-peck-crispy-chicken-allston-2",
    "Reviews": 27,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 3.7,
    "price_num": 2,
    "price": "$$",
    "type": "CHICKEN",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Venu Nightclub",
    "company_code": "A148",
    "Address": "100 Warrenton St",
    "Phone Number Combined": "(617) 338-8061",
    "Website": "Venuboston.Com",
    "Reviews": 156,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 3.3,
    "price_num": 3,
    "price": "$$$",
    "type": "DRINK",
    "cuisine": "Drink",
    "": null
  },
  {
    "Company_Name": "Wai Wai Ice Cream Shoppe",
    "company_code": "A149",
    "Address": "99 Harrison Ave",
    "Phone Number Combined": "(617) 338-3178",
    "Website": "https://www.yelp.com/biz/wai-wai-restaurant-boston",
    "Reviews": 108,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "DESSERT",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Wai Wai Restaurant",
    "company_code": "A150",
    "Address": "26 Oxford St",
    "Phone Number Combined": "(617) 338-9833",
    "Website": "https://www.yelp.com/biz/wai-wai-restaurant-boston",
    "Reviews": 108,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Watermark Donuts",
    "company_code": "A151",
    "Address": "626 Washington St",
    "Phone Number Combined": "(617) 426-9731",
    "Website": "http://recruiting.talentreef.com/watermark-donut-company",
    "Reviews": 7,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 2.6,
    "price_num": 1,
    "price": "$",
    "type": "DONUT",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Wilbur Theatre",
    "company_code": "A152",
    "Address": "246 Tremont St",
    "Phone Number Combined": "(617) 248-9700",
    "Website": "Libera.Org",
    "Reviews": 1621,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.2,
    "price_num": 3,
    "price": "$$$",
    "type": "THEATRE",
    "cuisine": "Other",
    "": null
  },
  {
    "Company_Name": "Wings Express Inc",
    "company_code": "A153",
    "Address": "65 Harrison Ave # 402",
    "Phone Number Combined": "Not Available",
    "Website": "http://wingexpressonline.com/",
    "Reviews": 132,
    "Credit_num": 4,
    "Credit_Score": "B+",
    "rates": 4.3,
    "price_num": 1,
    "price": "$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Wings Kitchen",
    "company_code": "A154",
    "Address": "23 Hudson St",
    "Phone Number Combined": "(617) 338-2218",
    "Website": "Calendar.Boston.Com",
    "Reviews": 52,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.5,
    "price_num": 1,
    "price": "$",
    "type": "AMERICAN",
    "cuisine": "American",
    "": null
  },
  {
    "Company_Name": "Winsor Dim Sum Cafe",
    "company_code": "A155",
    "Address": "10 Tyler St",
    "Phone Number Combined": "(617) 338-1688",
    "Website": "Winsordimsumcafe.Com",
    "Reviews": 780,
    "Credit_num": 5,
    "Credit_Score": "A",
    "rates": 4.1,
    "price_num": 1,
    "price": "$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  },
  {
    "Company_Name": "Yan's Best Place Restaurant",
    "company_code": "A156",
    "Address": "52 Beach St",
    "Phone Number Combined": "(617) 338-6223",
    "Website": "http://www.yansbistro.com/",
    "Reviews": 52,
    "Credit_num": 6,
    "Credit_Score": "A+",
    "rates": 4.6,
    "price_num": 2,
    "price": "$$",
    "type": "CHINESE",
    "cuisine": "Chinese",
    "": null
  }
];